Feature: added ability to override the default branch
awslabs/aws-deployment-framework pull request #370
Opened 2021-07-02 08:32 UTC by apogorielov

…pipelines

*Issue #, if available:*

*Description of changes:*

Following PR adds ability to override default "master" branch for deployment pipelines using values provided in adfconfig.yml. If parameter is not provided, branch defaults to "master" to remain backward compatibility.  

Priority of branch selection:
1. Deployment map branch configuration parameter.
2. Adfconfig default branch parameter.
3. Master branch. 

Parameter is propagated to the deployment accounts using SSM, where later is retrieved and used a part of input generation for pipelines. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-11-05 19:14 UTC, sbkok requested changes
Small change requested.
Other than that, looks good to me.

I wish we could default to main as the branch name. But unfortunately that would not be backward compatible. Something to consider for the next major release.

Thanks for contributing this change.

2021-11-05 19:14 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/example-adfconfig.yml
> +    default-scm-branch: master        # allow to specify custom defualt branch if pipeline specific is not provided. If parameter is not specified -  "master" branch will be used.
```suggestion
    default-scm-branch: master        # allow to specify custom default branch if a pipeline specific configuration is not provided. If the parameter is not specified it defaults to the "master" branch.
```

2021-11-05 19:16 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/example-adfconfig.yml
> +    default-scm-branch: master        # allow to specify custom defualt branch if pipeline specific is not provided. If parameter is not specified -  "master" branch will be used.
Could you also cover these settings in the documentation for administrators?

2021-11-18 16:58 UTC, sbkok approved these changes
I've pushed the changes requested in the review comments above.
Thanks for delivering this feature @apogorielov!

2021-11-18 17:11 UTC, StewartW approved these changes
Looks good to me :shipit:

2021-11-18 17:16 UTC, merged