F/fix partition python
awslabs/aws-deployment-framework pull request #381
Opened 2021-08-10 22:52 UTC by dsudduth

*Issue #, if available:*
#332

*Description of changes:*
This Pull Request adds support for GovCloud customers and regions. As described in #332, the changes focus on dynamically setting the partition.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-09-06 15:28 UTC, StewartW commented
This looks good @dsudduth . 
Thanks for the contribution! 

Would you be able to rebase it into a single (or fewer) commits though please?

2021-09-06 18:22 UTC, dsudduth commented
> This looks good @dsudduth .
> 
> I guess it makes: #343 redundant?
> Thanks for the contribution!
> 
> Would you be able to rebase it into a single (or fewer) commits though please?

Hi @StewartW,

I agree, #343 would no longer be needed. I've squashed the changes down significantly, keeping a few. Let me know if we need to change anything else. Thanks again for the review!

2021-11-05 16:25 UTC, sbkok requested changes

2021-11-05 17:34 UTC, dsudduth commented on src/lambda_codebase/cross_region_bucket/main.py
> +                f"trying another one ..."
Updated in latest commit.

2021-11-05 17:35 UTC, dsudduth commented on src/lambda_codebase/cross_region_bucket/main.py
> +
Updated in latest commit.

2021-11-05 17:35 UTC, dsudduth commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
> +      - "BUILD_GENERAL1_SMALL" #3 GB memory, 2 vCPU
Updated in latest commit.

2021-11-05 17:35 UTC, dsudduth commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
> +                  ]
Updated in latest commit.

2021-11-05 17:35 UTC, dsudduth commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
> +            ]
Updated in latest commit.

2021-11-05 17:35 UTC, dsudduth commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
> +            ]
Updated in latest commit.

2021-11-05 17:35 UTC, dsudduth commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py
> +
Updated in latest commit.

2021-11-05 18:39 UTC, sbkok approved these changes
Thanks a lot for following up with these changes so quickly.
And thank you for contributing, looks great to me!

2021-11-08 09:44 UTC, StewartW approved these changes
:shipit:  Changes look good. Thanks for making them

2021-11-08 10:52 UTC, merged