adding in ability to define CodeCommit artifact format
awslabs/aws-deployment-framework pull request #389
Opened 2021-09-17 08:14 UTC by StewartW

*Issue #, if available:* 
#387 

*Description of changes:*
Added in the ability to set the CodeCommit source provider property for output artifact format

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-11-08 19:35 UTC, sbkok requested changes
Thanks for adding this!
A few minor comments, if you could fix those we are good to go.

2021-11-08 19:35 UTC, sbkok commented on docs/providers-guide.md
> +- *output_artifact_format* - *(String)* default CODE_ZIP
```suggestion
- *output_artifact_format* - *(String)* default: `CODE_ZIP`
```

2021-11-08 19:35 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py
> +    Optional("output_artifact_format", default=None): Or(str, None)
```suggestion
    Optional("output_artifact_format", default=None): Or("CODEBUILD_CLONE_REF", "CODE_ZIP", None)
```

2021-11-08 19:35 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/tests/test_pipeline_creation.py
> +def test_pipeline_creation_outputs_as_expected_when_source_is_codecommit_with_codebuild_clone_ref_and_build_is_codebuild():
Can you update the test above this one to test that the `source_stage_action['Configuration']['OutputArtifactFormat']` is not set?

2021-11-12 09:59 UTC, sbkok approved these changes
LGTM, thanks for following up on the review and adding this feature!

2021-11-17 11:07 UTC, sbkok approved these changes

2021-11-17 13:02 UTC, thomasmcgannon approved these changes
lgtm

2021-11-17 14:15 UTC, merged