Reducing the number of IAM API calls made during enable cross-account…
awslabs/aws-deployment-framework pull request #408
Opened 2021-12-01 12:15 UTC by StewartW

… access

*Issue #, if available:* N/A

*Description of changes:*

I've changed the logic ever so slightly so that when enabling cross account access, it reduces the number of API calls  in the deployment account. Currently it will update the IAM policies per region (3 x Number of regions), meaning that it increases the chances of being throttled. 
This changes it to 3 API calls per account (or how many role/policy mappings are passed in). 

I've tried to make the change backwards compatible, just incase customers have downstream modifications to this lambda

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-12-10 17:50 UTC, sbkok requested changes
Minor suggestions only. Thanks for contributing this improvement!

2021-12-10 17:50 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/enable_cross_account_access.py
> +
Suggesting to remove one of the two empty lines:
```suggestion
```

2021-12-10 17:50 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_iam.py
> +
Requires another empty line before the new function:
```suggestion


```

2021-12-10 17:50 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_iam.py
> +
```suggestion


```

2021-12-12 13:52 UTC, sbkok approved these changes
LGTM, thanks!

2021-12-15 15:09 UTC, krisnielander approved these changes
lgtm

2021-12-17 13:45 UTC, merged