specify acl for S3 objects
awslabs/aws-deployment-framework pull request #412
Opened 2021-12-20 12:15 UTC by ivan-aws

Allows to specify the object ACL when using the S3 module. Uses `private` as the default, which was the implicit default before.

This allows to utilize different ACLs, like `bucket-owner-full-control` which is useful when operating with shared files.

Example:

```python
s3 = S3(<region>,<bucket>)

s3.put_object(
    s3_asset_key,
    file_asset_path,
    style="s3-url",
    pre_check=True,
    object_acl="bucket-owner-full-control",
)
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-12-20 13:20 UTC, ivan-aws commented
Updated tests in second commit. tests pass locally for me.

2021-12-28 09:29 UTC, sbkok requested changes
I've added a few style suggestions, nothing major.
Thanks for contributing this.

2021-12-28 09:29 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/s3.py
> +                                                            Body=file_handler)
```suggestion
                self.resource.Object(self.bucket, key).put(
                    ACL=object_acl,
                    Body=file_handler,
                )
```

2021-12-28 09:29 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_s3.py
> +        s3_object.put.assert_called_once_with(ACL='private',Body=mock_file.return_value)
```suggestion
        s3_object.put.assert_called_once_with(ACL='private', Body=mock_file.return_value)
```

2021-12-28 09:29 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_s3.py
> +        s3_object.put.assert_called_once_with(ACL='private',Body=mock_file.return_value)
```suggestion
        s3_object.put.assert_called_once_with(ACL='private', Body=mock_file.return_value)
```

2021-12-28 10:09 UTC, ivan-aws commented
Done!
As an alternative, may I recommend switching to an opinionated formatting tool, such as black? Formatting can then be automated as part of the PR process

2021-12-28 12:41 UTC, sbkok commented
Actually, I am working on adding automated formatting.
However, since that changes almost every line in our repository, I am waiting for our current PRs to be merged first.
Such that we don't need to modify as many PRs.

So most likely around releasing 3.2.0 I will add that to the repository.

2021-12-28 12:41 UTC, sbkok approved these changes
LGTM!

2022-08-10 15:27 UTC, sbkok approved these changes
LGTM, thanks!

2022-08-11 08:59 UTC, javydekoning approved these changes
LGTM! Thanks.

2022-08-12 13:35 UTC, merged