feat: encrypt sns topic using the ADF CMK KMS Key
awslabs/aws-deployment-framework pull request #429
Opened 2022-01-13 14:49 UTC by Nr18

*Issue #, if available:* #422

*Description of changes:*
Because ADF already has a KMS key that is used for encryption. It makes sense to use that key for the SNS notifications as well.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-01-17 08:36 UTC, StewartW submitted a review, later dismissed
Makes sense. 
Might be good to make it configurable going forward but I'm happy with that as is.

2022-02-01 11:21 UTC, sbkok requested changes
Thanks for contributing this @Nr18.

2022-02-01 12:29 UTC, Nr18 commented
Ah that makes sense! I applied your suggestion.

2022-02-02 09:41 UTC, StewartW approved these changes

2022-02-02 10:14 UTC, merged