Fix: #474 Generated Policy Size Too Long
awslabs/aws-deployment-framework pull request #475
Opened 2022-06-20 14:00 UTC by StewartW

*Issue #, if available:* #474

*Description of changes:*
[Broken down in the gist here](https://gist.github.com/StewartW/aff84e6f86811b128ca03b4d2014f559)

Separates out the policies for cloudformation-role in the target accounts and codepipeline role in the deployment account. 
Now have policies for S3, KMS and a base policy that catches everything else. 

Updated the shared IAM library to take in a list of policies to update now, also accepts single string and will treat it accordingly. 
Existing update policy code also provides backward compatibility because it checks if the statement with the SID exists in the policy and if it can't find it - it does nothing. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-10 15:16 UTC, sbkok requested changes
Only a few trailing space issues to be fixed. Except those it looks good, thanks!

2022-08-10 15:16 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
> +        - !Ref CloudFormationRole
```suggestion
        - !Ref CloudFormationRole
```

2022-08-10 15:16 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
> +        - !Ref CodePipelineRole
```suggestion
        - !Ref CodePipelineRole
```

2022-08-10 15:16 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
> +  CodePipelineRolePolicySTS:
```suggestion
  CodePipelineRolePolicySTS:
```

2022-08-10 15:16 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
> +  CodePipelineRolePolicyKMS:
```suggestion
  CodePipelineRolePolicyKMS:
```

2022-08-10 15:16 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml
> +        - !Ref CloudFormationRole
```suggestion
        - !Ref CloudFormationRole
```

2022-08-12 13:45 UTC, javydekoning approved these changes

2022-08-12 13:48 UTC, sbkok approved these changes
Thanks!

2022-08-12 13:48 UTC, merged