Fix: Lookup correct Organization API Region
awslabs/aws-deployment-framework pull request #485
Opened 2022-08-12 17:10 UTC by sbkok

**Why?**

At the moment, the organization API calls are made to the region where the `organizations.py` code is running.

However, which region to use depends on the partition that is in use.
For the US gov-cloud regions, it should use the `us-gov-west-1` region.
While the `aws` partition regions should use `us-east-1`.

**What?**

The code will determine the partition and return the correct region to use for the Organizations API.

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-12 19:42 UTC, StewartW approved these changes

2022-08-14 14:48 UTC, javydekoning requested changes
What about cn? Should we not also handle aws-cn (cn-northwest-1) as per https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations.html

Or otherwise just throw an error instead of defaulting to us-east-1?

2022-08-15 08:35 UTC, sbkok commented
Unfortunately, last time I checked the `cn` partition does not support all the services required for ADF to be installed.
I don't want to give a false hope to those that read these files and expect the `cn` partition to work out of the box.

2022-08-15 08:47 UTC, javydekoning commented
@sbkok , ack! Then what do you think about adding an if statement for the `aws` partition and Throwing an error on any other unsupported AWS region?

2022-08-15 12:39 UTC, sbkok commented
Good idea, I will add that.

2022-08-15 14:33 UTC, javydekoning approved these changes
Thanks for the changes and including tests! LGTM!

2022-08-15 14:58 UTC, StewartW approved these changes

2022-08-16 09:31 UTC, merged