Improve documentation style consitency by implementing Markdown lint
awslabs/aws-deployment-framework pull request #521
Opened 2022-09-04 08:40 UTC by javydekoning

*Issue #, if available:*
#491 

*Description of changes:*

- Enforce max line-length of 80
  - This applies to code blocks as well.
  - Exception are: 
    - `things-without-spaces` such as `[Link-to-console](https://which-frequently-exceeds-80)`
    - Markdown tables
- Rename `Master Account` to `Management account` as per recent AWS Changes
- Remove "quote" style lists items. Using `>` makes it difficult to make changes to list items as they need a `>` prefix per line. (changed to `-`)
- Enforce codefences to have a language
- Change file/path emphasis from "*somefile.txt*" to `somefile.txt`
- Enforce ordered lists to be `one_or_ordered`. Which means:

```md
1.
1.
1.
1.
```

Or

```md
1.
2.
3.
4.
```

Github will render both as incremental.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-09-05 11:35 UTC, StewartW approved these changes

2022-09-06 13:47 UTC, sbkok requested changes
Great improvement, thank you.

I took the liberty to review the lines that were changed.
So most of the comments are on the original documentation, not your PR.

Could you add the following string to the `EXECUTABLE_FILES` definition of `src/lambda_codebase/initial_commit/initial_commit.py`?
```py
    "adf-build/shared/helpers/terraform/install_terraform.sh",
```

The other files are out of scope for that initial commit handler or added already :)

2022-09-06 13:47 UTC, sbkok commented on docs/user-guide.md
> +|   |-- some-infra-pipeline.yml
To make it use the same structure as used in the `admin-guide.md` file with lists:

```suggestion
├───security/
|   ├───amazon-guardduty.yml
|   └───aws-config.yml
└───product-one/
    ├───roles/
    |   └───some-role-pipeline.yml
    └───infrastructure/
        └───some-infra-pipeline.yml
```

2022-09-06 13:47 UTC, sbkok commented on docs/user-guide.md
> +1:1 relationship, however, you can choose to clone or bring other repositories
```suggestion
1:1 relationship. However, you can choose to clone or bring other repositories
```

2022-09-06 13:47 UTC, sbkok commented on docs/user-guide.md
> +If you decide you no longer require a specific pipeline you can remove it from
```suggestion
If you decide you no longer require a specific pipeline, you can remove it from
```

2022-09-06 13:47 UTC, sbkok commented on docs/user-guide.md
> +Let's take a look an example to breakdown how the AWS Deployment Framework uses
```suggestion
Let's take a look at an example and breakdown how the AWS Deployment Framework uses
```

2022-09-06 13:47 UTC, sbkok commented on docs/user-guide.md
> +`generate_params.py`. The $S3_BUCKET_NAME variable is available in AWS CodeBuild
```suggestion
`generate_params.py`. The `$S3_BUCKET_NAME` variable is available in AWS CodeBuild
```

2022-09-06 13:47 UTC, sbkok commented on docs/user-guide.md
> +as we pass this in from our initial creation of the that defines the CodeBuild
```suggestion
as we pass this in from our deployment map that defines the CodeBuild
```

2022-09-06 13:47 UTC, sbkok commented on docs/user-guide.md
> +Otherwise you can add them into any pipelines specific buildspec.yml.
```suggestion
If the requirements are project specific, you can add them into the buildspec.yml
defined in the project itself.
```

2022-09-06 13:47 UTC, sbkok commented on docs/user-guide.md
> +will be the same across every deployment of your application however you might
```suggestion
will be the same across every deployment of your application. However, you might
```

2022-09-06 13:47 UTC, sbkok commented on docs/user-guide.md
> +`CONTAINS_TRANSFORM` environment variable to *True* in your pipeline definition
```suggestion
`CONTAINS_TRANSFORM` environment variable to `True` in your pipeline definition
```

2022-09-06 13:47 UTC, sbkok commented on docs/user-guide.md
> +your `buildspec.yml` file you will need to use the `package_transform.sh` helper
```suggestion
with a deployment map file. After defining the environment variable, update the
`buildspec.yml` file to call the `package_transform.sh` helper
```

2022-09-06 13:47 UTC, sbkok commented on docs/user-guide.md
> +template  for the pipeline deploy stages.
```suggestion
template for the pipeline deploy stages.
```

2022-09-06 13:47 UTC, sbkok commented on docs/user-guide.md
> +When you use the special keyword **"resolve:"**, the value in the specified
```suggestion
When you use the special keyword `resolve:`, the value in the specified
```

2022-09-06 13:47 UTC, sbkok commented on samples/sample-rdk-rules/README.md
> +account's config. AKA config role in target account(2222222222) should have the
```suggestion
account's config. AKA config role in the target account (2222222222) should have the
```

2022-09-06 15:24 UTC, javydekoning commented on CONTRIBUTING.md
> +someone else hasn't addressed the problem already.
Agreed! I'll do that.

2022-09-07 10:55 UTC, javydekoning commented
@sbkok I parsed all your comments. Should be much better now. Linter is not catching the list indents yet:

**GOOD**:

```md
1. this is some wrapped
   text
```

**BAD**:

```md
1. this is some wrapped
text
```

I'll submit a feature request for that.

2022-09-07 13:29 UTC, sbkok commented on docs/user-guide.md
> +exist you can use an optional resolve (e.g. `resolve:/my/path/to/myMagicKey?)`.
I think you might have missed this one, @javydekoning.

2022-09-07 13:39 UTC, sbkok requested changes
Much appreciated! Thanks for processing the changes.
Only one minor change to go and you would have my approval! :rocket:

2022-09-07 13:47 UTC, javydekoning commented on docs/user-guide.md
> +exist you can use an optional resolve (e.g. `resolve:/my/path/to/myMagicKey?)`.
I did miss it indeed. Fixed now.

2022-09-07 13:51 UTC, sbkok approved these changes
Great improvements to our code base, thank you for adding these!!

2022-09-14 13:11 UTC, StewartW approved these changes

2022-09-14 13:26 UTC, merged