feat(adf-bootstrap): (#472) modify trust relations for roles :zap:
awslabs/aws-deployment-framework pull request #526
Opened 2022-09-06 20:17 UTC by AndreasAugustin

*Issue #472 *

*Description of changes:*
Modify the trust relations for the roles.
Now a recreation of the related roles is possible without the need of a recreation for the adf stacks in all accounts.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-09-06 20:45 UTC, StewartW requested changes
I've requested a few changes and a comment. 

Thanks for raising the PR!

2022-09-06 20:45 UTC, StewartW commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml
> +              StringEquals:
```suggestion
              ArnEquals:
```

2022-09-06 20:45 UTC, StewartW commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml
> +              StringEquals:
```suggestion
              ArnEquals:
```

2022-09-06 20:45 UTC, StewartW commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml
> +              Fn::And:
This doesn't look right here. 
Are you trying to add both conditions in an AND fashion?

2022-09-06 20:45 UTC, StewartW commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml
> +              StringEquals:
```suggestion
              ArnEquals:
```

2022-09-06 20:45 UTC, StewartW commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml
> +              StringEquals:
ArnEquals

2022-09-06 20:52 UTC, StewartW commented
Hey @AndreasAugustin thanks for raising this PR. It's a great solution. 

Regarding the multi-block condition, is there any reason you wouldn't do it the same way as defined here: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html 

Rather than using the intrinsic AND operator.

2022-09-07 15:25 UTC, AndreasAugustin commented
> Hey @AndreasAugustin thanks for raising this PR. It's a great solution.
> 
> Regarding the multi-block condition, is there any reason you wouldn't do it the same way as defined here: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html
> 
> Rather than using the intrinsic AND operator.

Hi @StewartW thanks a lot for the review.
- fixed: `StringEquals` -> `ArnEquals`
- also moved from single quotes in some statements to double quotes
- `Fn::And` -> migrated to object based. I did not test it. At least `cfn-lint` is not complaining :+1:  I try to test it ASAP

2022-09-16 07:33 UTC, StewartW approved these changes

2023-06-08 09:52 UTC, javydekoning submitted a review, later dismissed

2023-07-24 13:26 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml
> +                "aws:PrincipalArn": !Sub "arn:${AWS::Partition}:iam::${DeploymentAccountId}:role/adf-lambda-role"
My mistake while merging, this is no longer in use. It got replaced by the the adf-automation roles instead.
```suggestion
```

2023-07-24 14:00 UTC, sbkok submitted a review, later dismissed
Great fix, thanks for contributing this!

2023-07-24 14:27 UTC, sbkok approved these changes

2023-07-24 15:25 UTC, javydekoning approved these changes

2023-07-24 15:33 UTC, merged