Instroduce CSpell linter
awslabs/aws-deployment-framework pull request #574
Opened 2022-12-16 11:42 UTC by javydekoning

# Why?

- Introducing CSpell to reduce the number of spelling mistakes in our code. 
- Also a first effort to reduce non inclusive language. 

Describe why you are proposing these changes

*Issue #, if available:*

For example, to avoid typo's such as: 
https://github.com/awslabs/aws-deployment-framework/pull/567

## What?

Description of changes:

- Added a custom dictionary under `/linters`
- Added (and removed from repo) blocked words: 'whitelist' and 'blacklist'
- Fixed spelling mistakes such as: 'TERIMIATION', 'MANGEMENT', 'DOESNT'.
- Enabled the linter in our megalinter config. 

---

By submitting this pull request, I confirm that you can use, modify, copy, and
redistribute this contribution, under the terms of your choice.

2022-12-16 15:12 UTC, sbkok requested changes
Thanks for adding this so quickly!
This well help a lot with reviewing code and ensuring typos don't accidentally end up in logical resource names as you mentioned.

I also agree on the inclusive wording. I worked on a branch a while ago to change the master account references into management account (in the code mainly), but I parked that until we can start working on the next major version.

2022-12-16 17:53 UTC, javydekoning commented on linters/custom-adf-dict.txt
> +stefanzweifel
[In the .github workflow](https://github.com/awslabs/aws-deployment-framework/blob/master/.github/workflows/mega-linter.yml#L68)

2022-12-16 17:56 UTC, javydekoning commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/create_or_update_rule.py
> +            {"MetricName": "CacheInitalized", "Value": 1, "Unit": "Count"}
Interesting, even my local CSpell plugin doesn't catch this typo....

2022-12-16 22:22 UTC, StewartW submitted a review, later dismissed
Looks good. Great addition. Ironic spelling mistake in the PR title is intentional yeah ;)

2022-12-20 10:22 UTC, sbkok approved these changes

2022-12-20 12:11 UTC, StewartW approved these changes

2022-12-20 12:23 UTC, merged