Feat: added support for distinct variable files per region per account in terraform pipelines
awslabs/aws-deployment-framework pull request #662
Opened 2023-10-16 08:55 UTC by igordust

# Why?

The current solution doesn't support different variable values per region in an account.

*Issue #661 

## What?

Description of changes:

- adf_terraform.sh, added the region folder management
- docs/user-guide.md, added documentation regarding the new feature

---

By submitting this pull request, I confirm that you can use, modify, copy, and
redistribute this contribution, under the terms of your choice.

2023-10-30 20:35 UTC, sbkok requested changes

2023-10-30 20:35 UTC, sbkok commented on src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/terraform/adf_terraform.sh
> +        cp -R "${CURRENT}/tfvars/${TF_VAR_TARGET_ACCOUNT_ID}/${AWS_REGION}"/* "${CURRENT}/tmp/${TF_VAR_TARGET_ACCOUNT_ID}-${AWS_REGION}"
To match the suggested fix in https://github.com/awslabs/aws-deployment-framework/pull/665, could you change this to the following? I.e. `/*` becomes `/.`.
```suggestion
        cp -R "${CURRENT}/tfvars/${TF_VAR_TARGET_ACCOUNT_ID}/${AWS_REGION}"/. "${CURRENT}/tmp/${TF_VAR_TARGET_ACCOUNT_ID}-${AWS_REGION}"
```

2023-10-31 08:03 UTC, sbkok approved these changes
LGTM, thank you!

2024-01-18 14:59 UTC, javydekoning approved these changes

2024-01-18 15:23 UTC, merged