add autoescape true
awslabs/aws-deployment-framework pull request #690
Opened 2024-02-22 12:59 UTC by sujay0412

# Why?

We are using aws-deployment-framework for deployments so In our AWS accounts we are solving  aws security hub findings .  one of the finding found called as CWE-20,79,80 - Cross-site scripting(XSS) with  high security labelled.
found Issue  in jinja2 library  in  initial_commit.py file there was no autoescape=True so  I added attribute as autoescape=True . After the changes  the finding related with XSS it solved for my aws account.
Please consider this in next release .

*Issue #, if available:*
Security-hub finding issue -CWE-20,79,80 - Cross-site scripting
User-controllable input must be sanitized before it's included in output used to dynamically generate a web page. Unsanitized user input can introduce cross-side scripting (XSS) vulnerabilities that can lead to inadvertedly running malicious code in a trusted context.

## What?

Description of changes:
1.Add autoescape= True for overcome XSS issue while creating template 
- List
- What
- You
- Changed
- 
1.in initial_commit.py file  in that def create_adf_config_file function in Jinja2 template code in def create_adf_config_file 
function 
adf_config = (
        jinja2.Template(template.read_text(), undefined=jinja2.StrictUndefined,autoescape=True)
        .render(vars(props))
        .encode()
    )
---

By submitting this pull request, I confirm that you can use, modify, copy, and
redistribute this contribution, under the terms of your choice.

2024-02-22 18:35 UTC, alFReD-NSH commented on src/lambda_codebase/initial_commit/initial_commit.py
> +        jinja2.Template(template.read_text(), undefined=jinja2.StrictUndefined,autoescape=True)
I'm not the right person to review this technically, but style-wise there should be a space after the comma:

```suggestion
        jinja2.Template(template.read_text(), undefined=jinja2.StrictUndefined, autoescape=True)
```

2024-03-14 03:53 UTC, sujay0412 commented
please review

2024-03-26 12:00 UTC, sbkok requested changes
Can you also add this change to the other Jinja2 Template call?
It is used here: [src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/initial_commit.py](https://github.com/awslabs/aws-deployment-framework/blob/ef662ece1227d62de105dda450c98f2d0d79b83e/src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/initial_commit.py#L513)

2024-04-05 06:17 UTC, sujay0412 commented
Hi @sbkok  based on your comment i updated a file which you mentioned please review , Thanks

2024-04-05 10:17 UTC, javydekoning approved these changes

2024-04-05 15:13 UTC, merged